# Generated by Django 3.1.3 on 2021-03-08 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_product', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая цена')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TV_stand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('long', models.CharField(max_length=255, verbose_name='Длина')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('depth', models.CharField(max_length=255, verbose_name='Глубина')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Straight_sofa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('transformation_mechanism', models.CharField(max_length=255, verbose_name='Механизм трансформации')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('length', models.CharField(max_length=255, verbose_name='Длина')),
                ('depth', models.CharField(max_length=255, verbose_name='Глубина')),
                ('filler', models.CharField(max_length=255, verbose_name='Наполнитель')),
                ('compartment_for_linen', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kitchen_Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('long', models.CharField(max_length=255, verbose_name='Длина')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('presence_of_drawers_for_dishes', models.CharField(max_length=255, verbose_name='Наличие ящиков для посуды')),
                ('table_opens', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hinged_shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('long', models.CharField(max_length=255, verbose_name='Длина')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('depth', models.CharField(max_length=255, verbose_name='Глубина')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Footwear_stand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('body_materials', models.CharField(max_length=255, verbose_name='Материалы корпуса')),
                ('facade', models.CharField(max_length=255, verbose_name='Фасад')),
                ('long', models.CharField(max_length=255, verbose_name='Длина')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('depth', models.CharField(max_length=255, verbose_name='Глубина')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dinner_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('countertop_materials', models.CharField(max_length=255, verbose_name='Материалы столешницы')),
                ('body_materials', models.CharField(max_length=255, verbose_name='Материалы корпуса')),
                ('long', models.CharField(max_length=255, verbose_name='Длина')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('width', models.CharField(max_length=255, verbose_name='Ширина')),
                ('unfolded_size', models.CharField(max_length=255, verbose_name='Размер в разложенном виде')),
                ('table_opens', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Cupboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('qty_doors', models.CharField(max_length=255, verbose_name='Количество дверей')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('long', models.CharField(max_length=255, verbose_name='Длина')),
                ('depth', models.CharField(max_length=255, verbose_name='Глубина')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Corner_sofa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('transformation_mechanism', models.CharField(max_length=255, verbose_name='Механизм трансформации')),
                ('angle_length', models.CharField(max_length=255, verbose_name='Длина угла')),
                ('length_of_corner_sofa', models.CharField(max_length=255, verbose_name='Длина углового дивана')),
                ('length_of_bed_of_corner_sofa', models.CharField(max_length=255, verbose_name='Длина спального места углового дивана')),
                ('bed_width_corner_sofa', models.CharField(max_length=255, verbose_name='Ширина спального места углового дивана')),
                ('compartment_for_linen', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Computer_desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('long', models.CharField(max_length=255, verbose_name='Длина')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('width', models.CharField(max_length=255, verbose_name='Ширина')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coffee_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('long', models.CharField(max_length=255, verbose_name='Длина')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('width', models.CharField(max_length=255, verbose_name='Ширина')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('qty_doors', models.CharField(max_length=255, verbose_name='Количество дверей')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('long', models.CharField(max_length=255, verbose_name='Длина')),
                ('depth', models.CharField(max_length=255, verbose_name='Глубина')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chest_of_drawers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('long', models.CharField(max_length=255, verbose_name='Длина')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('depth', models.CharField(max_length=255, verbose_name='Глубина')),
                ('qty_boxes', models.CharField(max_length=255, verbose_name='Количество ящиков')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('height', models.CharField(max_length=255, verbose_name='Высота')),
                ('depth', models.CharField(max_length=255, verbose_name='Глубина')),
                ('width', models.CharField(max_length=255, verbose_name='Ширина')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(default=0)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая цена')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='mainapp.cart', verbose_name='Корзина')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Покупатель')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='mainapp.CartProduct'),
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('bed_size_options', models.CharField(max_length=255, verbose_name='Варианты размеров спального места')),
                ('long', models.CharField(max_length=255, verbose_name='Длина')),
                ('width', models.CharField(max_length=255, verbose_name='Ширина')),
                ('compartment_for_linen', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Baby_bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('facade', models.CharField(max_length=255, verbose_name='Фасад')),
                ('bed_height', models.CharField(max_length=255, verbose_name='Высота кровати')),
                ('bed_length', models.CharField(max_length=255, verbose_name='Длина кровати')),
                ('bed_width', models.CharField(max_length=255, verbose_name='Ширина кровати')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категоря')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
